/**
 * @file exportConversation.ts
 * @description Generates and triggers download of a full conversation
 *   as a formatted Markdown file
 * @author [Author Placeholder]
 * @created 2026-07-01
 */

import { normalizeCitationMarkers } from './citationMarkers';

/**
 * Citation data structure for export formatting.
 */
export interface Citation {
  /** Citation index number */
  index: number;
  /** Source document filename */
  filename: string;
  /** Chunk index in the document */
  chunkIndex: number;
  /** Semantic similarity score (0-1) */
  similarity: number;
}

/**
 * Chat message structure for export.
 */
export interface ChatMessage {
  /** Message role */
  role: 'user' | 'assistant';
  /** Message text content */
  content: string;
  /** Optional citations for assistant messages */
  citations?: Citation[];
}

/**
 * Formats a date for filename use (YYYY-MM-DD).
 * @param date - Date object to format
 * @returns Formatted date string
 */
function formatDateForFilename(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Formats a date for display in the document header.
 * @param date - Date object to format
 * @returns Formatted date string
 */
function formatDateForDisplay(date: Date): string {
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Converts a full conversation array into a Markdown document string.
 * @param messages - Ordered array of chat messages
 * @returns Complete Markdown document as a string
 */
export function buildConversationMarkdown(messages: ChatMessage[]): string {
  const now = new Date();
  const header = `# RAG Knowledge Base — Research Session
*Exported: ${formatDateForDisplay(now)}*

---

`;

  if (messages.length === 0) {
    return `${header}*No messages in this conversation.*

---
*Generated by RAG Knowledge Base · groq/llama-3.1-8b-instant · HuggingFace all-MiniLM-L6-v2*`;
  }

  const body = messages
    .map((msg) => {
      const roleLabel = msg.role === 'user' ? '**You:**' : '**Knowledge Base:**';
      const normalizedContent = normalizeCitationMarkers(msg.content);
      
      let messageBlock = `${roleLabel} ${normalizedContent}\n`;

      // Add citations as blockquote for assistant messages
      if (msg.role === 'assistant' && msg.citations && msg.citations.length > 0) {
        const sources = msg.citations
          .map(
            (c) =>
              `[${c.index}] ${c.filename} · Chunk ${c.chunkIndex} · ${Math.round(c.similarity * 100)}% match`
          )
          .join('\n');
        messageBlock += `> Sources:\n> ${sources}\n`;
      }

      return messageBlock;
    })
    .join('\n---\n\n');

  const footer = `---
*Generated by RAG Knowledge Base · groq/llama-3.1-8b-instant · HuggingFace all-MiniLM-L6-v2*`;

  return `${header}${body}${footer}`;
}

/**
 * Triggers a browser download of the conversation as a .md file.
 * Uses URL.createObjectURL with a Blob — no server round-trip needed.
 * @param messages - Ordered array of chat messages
 */
export function downloadConversation(messages: ChatMessage[]): void {
  const markdown = buildConversationMarkdown(messages);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `rag-kb-conversation-${formatDateForFilename(new Date())}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
