/**
 * @file exportConversation.test.ts
 * @description Unit tests for exportConversation utility
 * @author [Author Placeholder]
 * @created 2026-07-01
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { buildConversationMarkdown, downloadConversation, type ChatMessage } from '../../utils/exportConversation';

describe('buildConversationMarkdown', () => {
  it('returns minimal header + footer for empty messages', () => {
    const result = buildConversationMarkdown([]);

    expect(result).toContain('# RAG Knowledge Base — Research Session');
    expect(result).toContain('*Exported:');
    expect(result).toContain('*No messages in this conversation.*');
    expect(result).toContain('*Generated by RAG Knowledge Base');
  });

  it('formats user message with correct "**You:**" label', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'What are the payment terms?' },
    ];
    const result = buildConversationMarkdown(messages);

    expect(result).toContain('**You:** What are the payment terms?');
  });

  it('formats assistant message with citations as blockquote sources', () => {
    const messages: ChatMessage[] = [
      {
        role: 'assistant',
        content: 'Payment is due within 30 days [1].',
        citations: [
          { index: 1, filename: 'contract.pdf', chunkIndex: 5, similarity: 0.91 },
        ],
      },
    ];
    const result = buildConversationMarkdown(messages);

    expect(result).toContain('**Knowledge Base:** Payment is due within 30 days [1].');
    expect(result).toContain('> Sources:');
    expect(result).toContain('> [1] contract.pdf · Chunk 5 · 91% match');
  });

  it('formats multiple exchanges with --- separators', () => {
    const messages: ChatMessage[] = [
      { role: 'user', content: 'What are the payment terms?' },
      {
        role: 'assistant',
        content: 'Payment is due within 30 days [1].',
        citations: [{ index: 1, filename: 'contract.pdf', chunkIndex: 5, similarity: 0.91 }],
      },
      { role: 'user', content: 'What happens if payment is late?' },
      {
        role: 'assistant',
        content: 'Late payments accrue interest [1].',
        citations: [{ index: 1, filename: 'contract.pdf', chunkIndex: 6, similarity: 0.84 }],
      },
    ];
    const result = buildConversationMarkdown(messages);

    const separatorCount = (result.match(/---/g) || []).length;
    expect(separatorCount).toBeGreaterThanOrEqual(3); // Header separator + message separators
  });

  it('normalizes Unicode superscript chars in messages', () => {
    const messages: ChatMessage[] = [
      {
        role: 'assistant',
        content: 'See section ① for details.',
        citations: [{ index: 1, filename: 'doc.pdf', chunkIndex: 1, similarity: 0.9 }],
      },
    ];
    const result = buildConversationMarkdown(messages);

    expect(result).toContain('See section [1] for details.');
  });
});

describe('downloadConversation', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('triggers blob download with correct filename format', () => {
    const mockCreateObjectURL = vi.fn().mockReturnValue('blob:url');
    const mockRevokeObjectURL = vi.fn();
    const mockClick = vi.fn();
    const mockAppendChild = vi.fn();
    const mockRemoveChild = vi.fn();

    globalThis.URL.createObjectURL = mockCreateObjectURL;
    globalThis.URL.revokeObjectURL = mockRevokeObjectURL;

    const mockLink = {
      href: '',
      download: '',
      click: mockClick,
    } as unknown as HTMLAnchorElement;

    document.createElement = vi.fn().mockReturnValue(mockLink);
    document.body.appendChild = mockAppendChild;
    document.body.removeChild = mockRemoveChild;

    const messages: ChatMessage[] = [{ role: 'user', content: 'Test' }];
    downloadConversation(messages);

    expect(mockCreateObjectURL).toHaveBeenCalled();
    expect(mockLink.download).toMatch(/^rag-kb-conversation-\d{4}-\d{2}-\d{2}\.md$/);
    expect(mockClick).toHaveBeenCalled();
    expect(mockRemoveChild).toHaveBeenCalled();
    expect(mockRevokeObjectURL).toHaveBeenCalledWith('blob:url');
  });

  it('cleans up object URL after download', () => {
    const mockCreateObjectURL = vi.fn().mockReturnValue('blob:url');
    const mockRevokeObjectURL = vi.fn();

    globalThis.URL.createObjectURL = mockCreateObjectURL;
    globalThis.URL.revokeObjectURL = mockRevokeObjectURL;

    const mockLink = {
      href: '',
      download: '',
      click: vi.fn(),
    } as unknown as HTMLAnchorElement;

    document.createElement = vi.fn().mockReturnValue(mockLink);
    document.body.appendChild = vi.fn();
    document.body.removeChild = vi.fn();

    downloadConversation([]);

    expect(mockRevokeObjectURL).toHaveBeenCalledWith('blob:url');
  });
});
